### ISSUE TITLE
how to trigger the WebAPI

### ISSUE THREAD

**Issue by XxDeadLiiNexX** [davidmchapman/3DContainerPacking#1]
Dear david,

thanks for this nice rebuild from the algorithm in c#.
a short question:
how can i trigger the web api, i have seen theres running a webserver with a api, must i send the data to it via json?
there is nothing in the documentation, when you me we could create a documentation together.
Greets.

**Comment by davidmchapman** [comment]
Hello!
The easiest way to launch the web app is to open the ContainerPacking solution file in Visual Studio. Then in the solution explorer right click the DemoApp project and click Set as StartUp Project. And then right click the container-packing.html file in the DemoApp project and click Set as Start Page. Then launch the app with F5. That should set everything up so you can use the page to make calls through the WebAPI.

On the page in your web browser, be sure to click the green plus sign next to the algorithm name to add that algorithm to the list to be used. Same if you manually add items or containers.

Then click Pack Em Up and it should give you results.

Does that help at all?

**Comment by XxDeadLiiNexX** [comment]
Dear David,

thanks for this exactly desription, i have forgotten to set the html as startup page, now it works!
But when i click "Pack Em Up", the Modal opens, but the Container View has no space ...
If i zoom in or out, the container is not longer here anymore.

Do you have a idea what happens here, or What I do wrong? (Browser Google Chrome, see Screenshot in the Attachment).

Greets from Austria.
![3dview](https://user-images.githubusercontent.com/10083729/27215654-9757ed7a-5272-11e7-8b65-0bccd81debe2.png)

**Comment by XxDeadLiiNexX** [comment]
Dear david,

its me again - sorry for the question before, to control the 3d container, i must hold the right click button. now everythink works. Thanks you for the help!

I hope i can write you by another questions 👍 
Greets from austria.

**Comment by XxDeadLiiNexX** [comment]
Dear David,

can you please start the 3d visualization with the following values from the screenshot below?
in my case, the algorithmus calculates the values, but the 3d presentation is empty, wyh is that?

![3dview_issue2](https://user-images.githubusercontent.com/10083729/27223555-38b2f96c-5291-11e7-9d93-9c7f533ad337.png)
![3dview_issue](https://user-images.githubusercontent.com/10083729/27223554-38b0fac2-5291-11e7-9909-a9b1e86f987b.png)

Info: i have copy my input into the attached text file.

[3dView_Issue_Input.txt](https://github.com/davidmchapman/3DContainerPacking/files/1080540/3dView_Issue_Input.txt)

Browser: google chrome
thanks you!
Greets from austria.

**Comment by XxDeadLiiNexX** [comment]
Dear David,

i think i have find the reason, this dimensions are so big, that the 3d view is only visible if you zoom longer in. But the correct presentation Still does not work, look at the scrrenshot:

![3dview_issue3](https://user-images.githubusercontent.com/10083729/27225858-615dc274-529c-11e7-9181-e6a25642349d.png)

Greets from austria.

**Comment by davidmchapman** [comment]
Hmm, yeah it looks like the visualization is struggling with items and containers with such large dimensions. I will need to look through the JS to see what is going on. Thanks for the heads up! In the meantime, you could try scaling everything down by a factor of 100 or so. All the relative dimensions will be the same, so the packing result should be identical. At least you will be able to see things that way.

**Comment by XxDeadLiiNexX** [comment]
Dear David,

Yes, you must zoom in very long...
Thanks, i have already used this "trick".

Greets from austria.

**Comment by FoxBatTango** [comment]
Rather than sending requests via WebAPI in order to view the results. Do you have the codes so that it may be developed locally? Thank you

**Comment by davidmchapman** [comment]
Hi, FoxBatTango. I went ahead and answered your question in the other issue you opened. Take a look over there and let me know if you have any other questions.

**Comment by FoxBatTango** [comment]
Thank you. I would like an example; I replied.

**Comment by debashis66** [comment]
Hi, I cannot locate the container-packing.html file in the repo/ demoapp project folder. Am I missing something ?
