### ISSUE TITLE
Is there any possibility to knwo the transformation of original box?

### ISSUE THREAD

**Issue by petrasvestartas** [davidmchapman/3DContainerPacking#13]
Hi,

Is there any possibility to know the transformation of original box to packed one?

By transformation I mean the rotation.

And is there any possibility to lock the rotations so that packed boxes would not be rotated?

**Comment by davidmchapman** [comment]
I would definitely like to see additional packing algorithms added to this library in the future. The EB-AFIT algorithm is going to keep its current functionality so it conforms with the behavior described in the original publication.
