### ISSUE TITLE
Rotation and Stacking

### ISSUE THREAD

**Issue by tempyzero** [davidmchapman/3DContainerPacking#18]
How it is possible to control rotation of certain items. Such as an Item cannot be rotated in specific Orientation. Also Does this Algorithm give ability to NO-TO-STACK-OVER certain items.
Ex. Some Heavy Items cannot be put above lighter Items.

Your Help Will be Greatly Appreciated. Thanks a Lot

**Comment by forceassaulter** [comment]
@tempyzero Have you solve the issue? I am facing the same problem as well.

**Comment by nms-dc** [comment]
@tempyzero @forceassaulter Hi Were you able to resolve this issue. Can you please give me some pointers as I am also stuck on the same issues that have been raised here. 

Thanks

**Comment by fgasnier71** [comment]
Version 3.0.2.28 coming at the end of the week will offer the possibility to set a priority for each item.

**Comment by nms-dc** [comment]
@fgasnier71 thank you so much. Will it be on this solution only?

**Comment by fgasnier71** [comment]
What do you mean?
In heterogeneous stacking, when defining items you will be able to set a priority. Items with priority 0 will be stacked before items of priority 1, which are stacked before items of priority 2...

**Comment by nms-dc** [comment]
That will certainly help. Thanks ! @fgasnier71

**Comment by fgasnier71** [comment]
Sorry, I am really confused. I thought I was answering some questions regarding my own project StackBuilder.

**Comment by nms-dc** [comment]
@fgasnier71 : Its for the 3d Bin Packing algorithm.  We have some business cases such as Priority of Items to be stacked at first etc. which we are attempting to solve.
