### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by forceassaulter** [davidmchapman/3DContainerPacking#19]
@davidchapman I am in a project and I need to arrange the boxes in a container where the door is at the front. I could not fully understand the code so I could not change the orientation. Can you please add more information to explain the code or to add new feature to choose which orientation to arrange first? Thank you.

**Comment by ronpack** [comment]
> @davidchapman I am in a project and I need to arrange the boxes in a container where the door is at the front. I could not fully understand the code so I could not change the orientation. Can you please add more information to explain the code or to add new feature to choose which orientation to arrange first? Thank you.

Did you ever find a solution to locking orientation?

**Comment by aleph79** [comment]
is it possible to block the rotation?

**Comment by davidmchapman** [comment]
The packing algorithm that is currently implemented does not allow blocking the rotation or specifying a "front" or other item/container orientations.
