### ISSUE TITLE
Teach Algorithmus do not put up items

### ISSUE THREAD

**Issue by XxDeadLiiNexX** [davidmchapman/3DContainerPacking#2]
Dear David,

is it possible to "teach" the algorithm do not put up items?

![3dview_issue4_putup](https://user-images.githubusercontent.com/10083729/27272644-877cb22c-54cb-11e7-830a-ecc93c62a794.png)

So the algorithmus should only lay down packes, what must i change in the algorithm that this is possible?

Greets from austria.

**Comment by davidmchapman** [comment]
Hi! This particular algorithm (EB-AFIT) allows full item rotation. The algorithm was designed by Erhan Baltacıoğlu in 2001 and is described in his master's thesis, available in PDF at [https://github.com/wknechtel/3d-bin-pack](https://github.com/wknechtel/3d-bin-pack). The algorithm could be modified to disallow item rotation, but you would probably need to read through the paper and the code to see where to make modifications.

**Comment by XxDeadLiiNexX** [comment]
Dear David,

thanks for your answer, i think this task takes long time.
If i find a solution, i post it for each.

greetings from austria.
