### ISSUE TITLE
Can you publish this lib as Nuget package

### ISSUE THREAD

**Issue by debashis66** [davidmchapman/3DContainerPacking#25]
It would be a great help if you could do that

**Comment by raphac** [comment]
There is already a nuget package for it: https://www.nuget.org/packages/CromulentBisgetti.ContainerPacking/
@davidchapman Maybe you could add something like this: https://github.com/davidmchapman/3DContainerPacking/pull/23/commits/ab4a4cfd769917cfd96ee90cd06b4fd8fc6caaf5

**Comment by davidmchapman** [comment]
Badge added to readme. Thanks for the suggestion, and sorry I was away from the project for so long!
