### ISSUE TITLE
Bug + fix found in reference implementation

### ISSUE THREAD

**Issue by MarkusFaatz** [davidmchapman/3DContainerPacking#26]
Hey there!
I recently searched for the EB-AFIT algorithm and I found [this bug](https://github.com/wknechtel/3d-bin-pack/issues/2) in the original C-Code project that seems to have also found his way to this C# project. 

As [Robertson](https://github.com/robertson-so) also suggests a fix you might have a look at these two lines in your code

https://github.com/davidmchapman/3DContainerPacking/blob/7f24c7be65fda78205707befb2c1dd98167d1e08/src/CromulentBisgetti.ContainerPacking/Algorithms/EB_AFIT.cs#L940-L941

where it might be a mistake to decrement `cboxx` twice from the `itemsToPack[cboxi].CoordX`

**Comment by davidmchapman** [comment]
Very interesting! I'm open to updating the code. I've taken time away from this project but now have some more time to hop back into it. Soon I will run the tests on the before and after code to see how this affects them. I'll report back.

Thank you for bringing this up!

**Comment by davidmchapman** [comment]
I was able to verify both the issue and the proposed fix.

Following [the original comment](https://github.com/wknechtel/3d-bin-pack/issues/2#issue-551831721) from @garrettsickles, I ran the packing algorithm on set 4 of the randomly generated problem sets from Appendix D of the original master's thesis. This test attempts to pack 1000+ items into a single 104x96x84 container.

Packing with the unfixed code yielded the same issue @garrettsickles noted, shown here:
![box94-1](https://user-images.githubusercontent.com/22284869/109441765-c8599b80-79fb-11eb-9d4b-32892b5dd9ec.png)

Notably, you can also see where the accidental shifting started in this layer. That's what pushed the final item in the layer outside the bounds of the container:
![box94-2](https://user-images.githubusercontent.com/22284869/109441782-d60f2100-79fb-11eb-8fa7-4538c09c79f9.png)

With the proposed fix, the algorithm correctly closes that gap:
![box94-fixed](https://user-images.githubusercontent.com/22284869/109441794-df988900-79fb-11eb-9aef-5749b28c79e7.png)

Great work, @garrettsickles, @robertson-so, and @MarkusFaatz!!

I will roll the fix into master in this repo soon. Thanks, everyone!

**Comment by davidmchapman** [comment]
Fix committed.

**Comment by luenib** [comment]
So, how are the lines 940 and 941 supposed to look like once the bug is fixed?
