### ISSUE TITLE
Question: Find largest containers that fits inside volume

### ISSUE THREAD

**Issue by michaldengusiak** [davidmchapman/3DContainerPacking#29]
Hi,
Would be possible to find the largest container that fit into the shape. 
We are looking for some nice centre point inside 3D geometry. So I thought we could get the largest volume container and its middle of diagonal using your workflow. Not sure if this would work...or maybe you have some idea? 
Does it work if we have volume like doughnut shape?
What are the limitation yo my volumes?

**Comment by davidmchapman** [comment]
Hmm, I'm not sure this project would help with that. This packing algorithm treats everything as solid cuboids, so it wouldn't know what to do with differently shaped volumes.

**Comment by michaldengusiak** [comment]
ok thanks for the reply...yes in my case I need more flexibility...
