### ISSUE TITLE
Looks like I set it all up right but I get a javascript error

### ISSUE THREAD

**Issue by speedy32129** [davidmchapman/3DContainerPacking#3]
So the error is JavaScript critical error at line 8, column 7 in http://localhost:59023/js/container-packing.js\n\nSCRIPT1004: Expected ';'

Any clue?

**Comment by davidmchapman** [comment]
Hi! Sorry for the delayed response. I wasn't checking in regularly.
I have not run into that error with this demo app. What browser are you testing in?

**Comment by davidmchapman** [comment]
This might be related to my use of async/await syntax in the JS file. Did you try loading the page in Chrome? I did not do any cross-browser testing of the demo.
