### ISSUE TITLE
Algorithm not giving result 

### ISSUE THREAD

**Issue by dharmendrasingh88** [davidmchapman/3DContainerPacking#36]
Hi David,
I have downloaded this lib after your latest update.
Now issue that no algorithm output results for any container.
Can you please suggest what might be I am missing?
https://www.loom.com/share/6a9613c9807649338ba9a7f9f771bf7b

**Comment by PhillipRt** [comment]
This might be a little unintuitive, but you need to add the "Algorithm to Use". Click the green plus next to the "EB-AFIT" dropdown.

**Comment by dharmendrasingh88** [comment]
@PhillipRt  Correct Algorithm type was not passing to the controller.I have fixed this now its working like charm
