### ISSUE TITLE
Possible implementations?

### ISSUE THREAD

**Issue by gabryone** [davidmchapman/3DContainerPacking#6]
Thanks for this fantastic library!

Is it possible to implement this library for further functionality? 

Example:

- **Load Side**
The loading side specifies the open part of the container from where the boxes can
be loaded. The Load Side can be in 3 way:
a. For Width side: the boxes will be loaded from Width side
b. For Length side: the boxes will be loaded from Length side
c. For Top side: the boxes will be loaded from Top side
![image](https://user-images.githubusercontent.com/18192344/36698517-505a117c-1b4a-11e8-9da7-61735db1c61c.png)

- **Load Direction**
The Load Direction is defined in this way:
a. From Left to Right: the boxes will be loaded from left to right
b. From Right to Left: the boxes will be loaded from right to left
in both cases the load will go from back to front (or from below to above)
The following examples explain the load direction, red is the primary direction, blue is the secondary direction.
Load direction example “Left to Right” in Width load side.
![image](https://user-images.githubusercontent.com/18192344/36698688-ca88d852-1b4a-11e8-93e7-c68a128df938.png)
Load direction example “Right to Left” in Width load side.
![image](https://user-images.githubusercontent.com/18192344/36698698-d021bcac-1b4a-11e8-92e0-3468c43b90de.png)
Load direction example “Left to Right” in Length load side.
![image](https://user-images.githubusercontent.com/18192344/36698706-d4d9e3a0-1b4a-11e8-88b8-bf576722a332.png)
Load direction example “Right to Left” in Length load side.
![image](https://user-images.githubusercontent.com/18192344/36698724-deaf6968-1b4a-11e8-91bc-b3dab3ccc5ce.png)
Load direction example “Left to Right” in Top load side.
![image](https://user-images.githubusercontent.com/18192344/36698734-e51dbc96-1b4a-11e8-88f8-cc11200ac4b0.png)
Load direction example “Right to Left” in Top load side.
![image](https://user-images.githubusercontent.com/18192344/36698741-e996097c-1b4a-11e8-8029-0cedbe74191f.png)

- **Box Stackable** (boolean)
If false, no box can be placed on above, but it can be place above other box.

- **Box Sorting** (int)
More lower the sorting is, and more first be processed. If 0, the sorting is irrelevant. This property is useful if you have boxes that must be left closer to the loading side to be able to download them before the others. Or for an order, if we think of a courier who has to make orderly deliveries. Example: we could have 7 boxes with a sorting 1, 3 with another sorting 2, 9 with another 3, etc. All boxes with the same number go close to be downloaded in the same moment.

- **Use Weight Distribution** (boolean)
This property define if the process use the weight distribution.
With the weight distribution the load must be distributed uniformly for each container so that there are no points where the weight is too high compared to other points of the load. _This feature need to have a Box Weight property._

- **Use Stability Constraint** (boolean)
This property define if the process use the stability constraint. If use, the boxes must be stable.
Stable box means that box is supported by container floor or top of other box. Also at least 3 side of box is supported by container or other box.
![image](https://user-images.githubusercontent.com/18192344/36699014-c3257dee-1b4b-11e8-9768-16199378abad.png)

- **Type Of Saving**
This property define the Nesting process.
There are two way:
a. **Space** The processing will use the containers optimally saving space, and using the fewest containers and possibly the smallest ones. Which is what the algorithm does now, I think.
b. **Cost** The processing will use the containers optimally saving costs, choosing the containers that will cost less the total processing. _This feature need to have a Container Cost property._

**Comment by EdgarSalazar** [comment]
This is nice. I'm pretty sure it can be implemented, since it's based on a thesis. But I think Mr. @davidmchapman stopped working on this, he's just gone.

**Comment by davidmchapman** [comment]
My bad for never responding to this. My feeling is that the base EB-AFIT algorithm should be left as-is. I would love to see various enhancements like the ones proposed in this issue, but they should probably be implemented as their own, independent algorithms. They could be named as variations of EB-AFIT if they share substantial code or methodology as the base algorithm. The packing service can already support multiple algorithms, they just need to implement the interface. I will probably need to leave it up to others to write the variations they would like to see because my free time is pretty constrained lately. If anyone wants to contribute a new variation, or an entirely new algorithm, please submit a pull request. Thanks!!

**Comment by EdgarSalazar** [comment]
@davidchapman  I'm sorry I said you were gone. Clearly, I was wrong. I agree with you, the algorithm should stay faithful to the thesis. A new algorithm can be implemented to extend the funcionality.

**Comment by Jhutchings5** [comment]
Is it possible to have a tooltip on the items in the container?  No matter what I try, I cant seem to be able to hover on the correct item in the wireframe (container)

**Comment by davidmchapman** [comment]
@Jhutchings5, the web-based demo is just a quickly thrown together application to demonstrate that the packing library packs as intended. I don't have plans to augment its functionality since it is just a demo.

**Comment by nk-alex** [comment]
I'm really interested in the "Use Stability Constraint" feature. Can I get some guidance in the topic? I opened an [issue](https://github.com/davidmchapman/3DContainerPacking/issues/52) myself.

My supposition is I should give packing priority to bigger items. So I should order items by volume before running the algorithm and then, somehow, chage [AnalyzeBox](https://github.com/davidmchapman/3DContainerPacking/blob/4a6102f5b6bb67a230a2d12326052b3da6341b51/src/CromulentBisgetti.ContainerPacking/Algorithms/EB_AFIT.cs#L123) function.
