### ISSUE TITLE
item direct control

### ISSUE THREAD

**Issue by Dragonkingpan** [davidmchapman/3DContainerPacking#7]
thank you for your programe.
i want to know how can i put my item to container without scale change.
for example:
i have a container with: 3x1x3
and have a item size is: 1x2x2
when i run application, it put item to container, with size 2x1x2. it is ok.
i want to set a param make the item not put in container.

**Comment by davidmchapman** [comment]
The EB-AFIT packing algorithm allows full rotation of both the items and the container. You would need to use a different algorithm if you do not want to allow item or container rotation.
