### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by DougPlumley** [davidmchapman/3DContainerPacking#8]
I'm rather new to GitHub/public code, so apologizes if I've overlooked something.  Is there a license for this code?  I'd potentially like to use it for calculating postage for packages for commercial use.

I looked at some of the referenced GitHub repos you used and didn't immediately see licenses on them either.

Thanks!

**Comment by ethno2405** [comment]
Hi. I would like to use this library in a commercial application and fork it. According to section 2 [here](https://opensource.guide/legal), I am not able to do it safely.

**Comment by davidmchapman** [comment]
Hello! Would the MIT license suit your needs?

**Comment by davidmchapman** [comment]
Added MIT license to the repo.
