### ISSUE TITLE
Enhancement suggestion

### ISSUE THREAD

**Issue by hotfirewire** [davidmchapman/3DContainerPacking#9]
First off thank you for this.  It's amazing how little there is in C# for the 3D Bin Packing problem.  I do have a feature enhancement suggestion that you might want to consider.  Some shippers have a weight limit for boxes and it would be beneficial if you could add a max weight for containers.  This way you wont get overloaded on packing containers.  

Thanks again!

**Comment by davidmchapman** [comment]
Thank you for the comment. Could that be a pre- or post-processing step in the client application? I think keeping the packing algorithm purely focused on spatial packing has benefits, and then clients are free to impose additional rules as applicable. For example, if we have a set of items, and we know that the entire set will exceed the weight restriction of the shipper, then in a pre-processing step the application could run some logic to prune the item list and pack only a subset. Does that formulate the problem correctly?
